import { test, expect } from '@playwright/test';

/**
 * Example test generated by Playwright Orchestrator.
 * Replace BASE_URL with your target application URL.
 * Run: npx playwright test tests/examples/sample.spec.ts
 */
test.describe('Sample: Page Load', () => {
  test('page loads with valid title', async ({ page }) => {
    await page.goto('/');
    await expect(page).toHaveTitle(/.+/);
    await page.waitForLoadState('networkidle');
  });

  test('no console errors on load', async ({ page }) => {
    const errors: string[] = [];
    page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()); });
    await page.goto('/');
    await page.waitForLoadState('networkidle');
    expect(errors, `Console errors: ${errors.join(', ')}`).toHaveLength(0);
  });
});

test.describe('Sample: Navigation', () => {
  test('URL is reachable', async ({ page }) => {
    const response = await page.goto('/');
    expect(response?.status()).toBeLessThan(400);
  });
});
