/** Every platform table, parents before children. */
export const PLATFORM_TABLES = [
  'users',
  'sessions',
  'audit_logs',
  'projects',
  'project_environments',
  'test_scripts',
  'test_script_versions',
  'tags',
  'script_tags',
  'skills',
  'skill_versions',
  'skill_tags',
  'project_skills',
  'script_skills',
  'jenkins_configurations',
  'project_ci_jobs',
  'test_executions',
  'execution_scripts',
  'execution_results',
  'execution_logs',
  'execution_skill_snapshots',
  'healing_proposals',
] as const;
